import os
import yaml
from yacs.config import CfgNode as CN
from .styles import *

_C = CN()

# Base config files
_C.BASE = ['']

_C.SEMANTIC = CN()
_C.SEMANTIC.DEFAULT_EXPORT_STYLE = COCO

_C.COLOR = CN()
_C.COLOR.DEFAULT_EXPORT_FORMAT = 'rgb'
_C.COLOR.DEFAULT_RANDOM_HUE_RANGE = (0, 1)
_C.COLOR.DEFAULT_RANDOM_LIGHTNESS_RANGE = (0.35, 0.7)
_C.COLOR.DEFAULT_RANDOM_SATURATION_RANGE = (0.6, 1)

_C.ANNOTATION = CN()

_C.ANNOTATION.MASK = CN()
_C.ANNOTATION.MASK.POLYGON_APPROX_METHOD = 'KCOS'
_C.ANNOTATION.MASK.DEFAULT_MATCH_THRESHOLD = 0.5

_C.ANNOTATION.POLYGON = CN()
_C.ANNOTATION.POLYGON.EXPORT_SIMPLIFIED = True
_C.ANNOTATION.POLYGON.EXPORT_SIMPLIFY_EPSILON = 2

_C.IMAGE = CN()
# _C.IMAGE.USE_RELATIVE_PATH = False
# _C.IMAGE.IMAGE_ROOT = ''

_C.IMAGE.DRAW = CN()
_C.IMAGE.DRAW.DEFAULT_COLOR_BY_CATEGORY = False

_C.IMAGE.DRAW.DEFAULT_DRAW_BBOX = True
_C.IMAGE.DRAW.DEFAULT_BBOX_THICKNESS = 2

# _C.IMAGE.DRAW.DEFAULT_DRAW_POLYGON = True
_C.IMAGE.DRAW.DEFAULT_POLYGON_THICKNESS = 3

_C.IMAGE.DRAW.DEFAULT_DRAW_MASK = True
_C.IMAGE.DRAW.DEFAULT_MASK_ALPHA = 0.5

_C.IMAGE.DRAW.DEFAULT_DRAW_OUTLINE = True
_C.IMAGE.DRAW.DEFAULT_OUTLINE_THICKNESS = 3

_C.IMAGE.DRAW.DEFAULT_DRAW_TEXT = True
_C.IMAGE.DRAW.DEFAULT_TEXT_SCALE = 0.5


_C.DATASET = CN()

